"""add profile_picture to user

Revision ID: 413cb94a4d19
Revises: 264b1f76c273
Create Date: 2024-07-06 15:31:47.524010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '413cb94a4d19'
down_revision = '264b1f76c273'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=256), nullable=True))
        batch_op.alter_column('about_me',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.String(length=280),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('about_me',
               existing_type=sa.String(length=280),
               type_=sa.VARCHAR(length=140),
               existing_nullable=True)
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###
