"""Change body field to Text for blog posts

Revision ID: a9015e3f7131
Revises: a39f0412b997
Create Date: 2024-07-04 22:07:10.856879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9015e3f7131'
down_revision = 'a39f0412b997'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('about_me',
               existing_type=sa.VARCHAR(length=280),
               type_=sa.String(length=560),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('about_me',
               existing_type=sa.String(length=560),
               type_=sa.VARCHAR(length=280),
               existing_nullable=True)

    # ### end Alembic commands ###
